In [1]:
# Librerias
import pandas as pd

In [ ]:
# 1- PREPARAMOS LOS DATOS.
df_seguros = pd.read_csv('Dataset_de_Seguros_Actualizado.csv',sep=',')
df_seguros

,ID_Cliente,Edad,Prima_Seguro,Tipo_Seguro,Genero,Antiguedad_Cliente_Anios,Reclamos_Anuales,Provincia,Canal_Contratacion,Tiene_Descuento,Satisfaccion_Cliente
0,1,56,4737.44,Auto,M,0,0,Misiones,Online,0,3
1,2,69,13342.43,Vida,M,6,0,Mendoza,Online,0,3
2,3,46,5329.27,Tecnología,F,10,0,Entre Ríos,Agente,0,3
3,4,32,11128.12,Viaje,M,1,1,Misiones,Sucursal,1,1
4,5,60,12809.77,Auto,M,0,4,Córdoba,Sucursal,0,3
...,...,...,...,...,...,...,...,...,...,...,...
995,996,37,16674.24,Auto,M,7,2,Mendoza,Online,0,2
996,997,41,13030.21,Auto,F,7,1,Corrientes,Online,0,1
997,998,22,13645.09,Auto,M,0,2,Corrientes,Online,0,4
998,999,51,11299.78,Viaje,M,8,0,Buenos Aires,Online,1,4
999,1000,23,15102.46,Auto,M,1,2,Tucumán,Teléfono,0,3

In [5]:
df_seguros2 = pd.read_csv('Dataset_de_seguros.csv',sep=',')
df_seguros2

,ID_Cliente,Edad,Prima_Seguro,Tipo_Seguro,Genero,Antiguedad_Cliente_Anios,Reclamos_Anuales,Provincia,Canal_Contratacion,Tiene_Descuento,Satisfaccion_Cliente
0,1002,63,24068.44,Salud,M,8,2,Corrientes,Teléfono,0,3
1,1003,35,7457.25,Salud,F,3,1,Santa Fe,Online,0,3
2,1004,26,10430.74,Vida,F,4,4,Salta,Agente,0,4
3,1005,71,8365.58,Salud,F,2,0,Entre Ríos,Sucursal,0,4
4,1006,58,10823.10,Auto,F,13,1,Chaco,Teléfono,0,3
...,...,...,...,...,...,...,...,...,...,...,...
1495,2497,72,13368.43,Salud,F,5,0,Corrientes,Agente,0,4
1496,2498,47,7669.59,Hogar,F,8,1,Misiones,Sucursal,0,3
1497,2499,51,9686.74,Hogar,F,0,0,Santa Fe,Teléfono,0,5
1498,2500,56,11828.36,Salud,F,12,2,Buenos Aires,Online,0,3
1499,2501,26,12504.87,Vida,F,10,2,Chaco,Online,1,4